POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Another blog",
    "author": "Vlad Slivilescu",
    "url": "http://www.google.com",
    "likes": 120
}

###
GET http://localhost:3003/api/blogs